import { Fragment } from "react"
import Head from "next/head"
import Image from "next/image"

import Footer from "@/components/Footer"
import Section from "@/components/layout/Section"
import Button from "@/components/Button"

import { BsArrowRightShort } from "react-icons/bs"
import asset_logo from "@/assets/logo.png"

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Hook.Monster | The on-chain IFTTT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>
      <nav className="p-4 border-b border-zinc-100">
        <div className="flex items-center justify-between gap-8 mx-auto max-w-screen-xl">
          <Image height={48} src={asset_logo} alt="hook.monster logo" />
          <div className="flex-grow text-gray-600 hidden md:flex items-center gap-4 justify-end">
            <div className="hover:text-black">Services</div>
            <div className="hover:text-black">Pricing</div>
            <div className="hover:text-black">Docs</div>
          </div>
          <Button className="flex gap-2 group items-center" flavor="black">
            <span>
              Launch <span className="hidden md:inline">App</span>
            </span>
            <BsArrowRightShort className="text-3xl group-hover:translate-x-px" />
          </Button>
        </div>
      </nav>
      <Section className="min-h-screen">
        <div className="mx-auto mt-[15vh] max-w-3xl min-h-screen text-center">
          <h1 className="bg-gradient-to-r from-pink-500 py-4 via-red-500 to-yellow-500 bg-clip-text text-4xl sm:text-6xl font-bold text-transparent">
            Hook any blockchain event with a single click
          </h1>
          <p className="mx-auto text-sm sm:text-base text-gray-600 max-w-2xl sm:leading-relaxed">
            Query smart contracts, events and forward them on Discord or
            Telegram. Send custom notifications for your users. Monitor and
            automate on-chain activity
          </p>
          <Button
            className="flex gap-2 group items-center text-xl mx-auto mt-12"
            flavor="pink"
          >
            <span>Get started for free</span>
            <BsArrowRightShort className="text-3xl group-hover:translate-x-px" />
          </Button>
        </div>
      </Section>
      <Footer />
    </Fragment>
  )
}
