import { Fragment } from "react"
import Head from "next/head"
import Image from "next/image"

import asset_logo from "@/assets/logo.png"
export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Hook.Monster | The on-chain IFTTT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen p-8">
        <nav className="flex border-b pb-8">
          <Image height={64} src={asset_logo} alt="hook.monster logo" />
        </nav>
        <h1 className="mt-12 text-5xl font-bold max-w-xl">
          Pipe on-chain events to the off-chain world easy.
        </h1>
        <p className="max-w-md text-xl mt-4 text-zinc-700">
          Turn smart contracts into APIs. Web3 notifications for your users.
          Query, trigger, monitor and automate chain activity easily.
        </p>
      </main>
      <footer className="p-8 flex justify-center border-t">
        <a href="https://vercel.com" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </a>
      </footer>
    </Fragment>
  )
}
